name = "wnm_pgb1_simulator"
description = "Simulator of the PGB-1 groovebox"
version = "1.0.1"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm-pgb1-simulator"]

[[depends-on]]
asfml = "^2.5.2"
hal = "~1.0.0"
resources = "~0.1.0"
littlefs = "~1.0.0"
rtmidi = "~0.1.0"
fsmaker = "~0.0.0"
flux = "~1.0.0"
stopwatch = "~0.1.0"
tresses = "~1.0.0"
uf2_utils = "*"
midi = "^1.0.0"

[[pins]]
fsmaker = { url="https://github.com/Fabien-Chouteau/fsmaker" }
uf2_utils = { url="https://github.com/Fabien-Chouteau/uf2_utils" }

[configuration.values]
littlefs.Assert = false
littlefs.Debug = false
littlefs.Warn = true
littlefs.Error = true
littlefs.Trace = false
littlefs.No_Malloc = true
tresses.Sample_Rate = "SR32000"

[build-switches]
"*".ada_version = "ada2022"

# [build-profiles]
# fsmaker = "development"
# littlefs = "development"

[environment.'case(distribution)'.msys2.CPLUS_INCLUDE_PATH]
append = "${DISTRIB_ROOT}/mingw64/include"
