name = "wnm_ps1_simulator"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_ps1_simulator"]

[[depends-on]]
asfml = "^2.5.2"
hal = "~0.3.0"
resources = "~0.1.0"
littlefs = "~0.1.0"
lpc_synth = "~0.1.0-dev"
rtmidi = "~0.1.0"
fsmaker = "~0.0.0"
flux = "~0.1.0-dev"
stopwatch = "~0.1.0"
tresses = "*"

[[pins]]
fsmaker = { url="https://github.com/Fabien-Chouteau/fsmaker" }
littlefs = { url = "https://github.com/Fabien-Chouteau/littlefs-ada", branch="release/0.3" }
lpc_synth = { url="https://github.com/Fabien-Chouteau/lpc_synth" }
flux = { url="https://github.com/Fabien-Chouteau/flux" }
tresses = { url="https://github.com/wee-noise-maker/tresses" }

[configuration.values]
littlefs.Assert = false
littlefs.Debug = false
littlefs.Warn = true
littlefs.Error = true
littlefs.Trace = false
# littlefs.No_Malloc = true # Triggers a bug in alr 1.2.1, var set in fsmaker anyway
tresses.Sample_Rate = "SR44100"

[build-switches]
"*".ada_version = "ada2022"
[gpr-set-externals]
BBQUEUE_COMPILE_CHECKS = "disabled"
BBQUEUE_RUNTIME_CHECKS = "disabled"
BBQUEUE_CONTRACTS = "disabled"
