name = "wnm_pgb1_device"
description = "Firmware for the PGB-1 groovebox"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_pgb1_device"]

[[depends-on]]
tresses = "*"
lpc_synth = "~0.1.0-dev"
littlefs = "~0.1.0"
flux = "~0.1.0-dev"
noise_nugget_sdk = "*"
midi = "^1.0.0"

[[pins]]
flux = { url="https://github.com/Fabien-Chouteau/flux" }
lpc_synth = { url="https://github.com/Fabien-Chouteau/lpc_synth" }
littlefs = { url = "https://github.com/Fabien-Chouteau/littlefs-ada", branch="release/0.3" }
tresses = { path = "../../tresses" }
midi = { path = "../../midi" }
noise_nugget_sdk = { path = "../../noise-nugget-ada-sdk" }
rp2040_hal = { url="https://github.com/JeremyGrosser/rp2040_hal" }

[build-switches]
"*".ada_version = "ada2022"

[configuration.values]
noise_nugget_sdk.System_Clock = "SYS_133MHz"
littlefs.Assert = false
littlefs.Debug = false
littlefs.Warn = false
littlefs.Error = false
littlefs.Trace = false
littlefs.No_Malloc = true
tresses.Sample_Rate = "SR32000"
# tresses.Resources_Linker_Section = ".time_critical.tresses_resources"
# tresses.Code_Linker_Section = ".time_critical.tresses_code"
flux.Enable_File_IO = false

[build-profiles]
# noise_nugget_sdk = "development"
# rp2040_hal = "development"
# littlefs = "development"
