name = "wnm_pgb1_device"
description = "Firmware for the PGB-1 groovebox"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_pgb1_device"]

[[depends-on]]
tresses = "~2.0.0"
littlefs = "~1.0.0"
flux = "~1.0.0"
noise_nugget_sdk = "*"
midi = "~1.0.0"

[[pins]]
noise_nugget_sdk = { url = 'https://github.com/wee-noise-makers/noise-nugget-ada-sdk', commit = "631ca2ed2d8c3fa66320a72daf8b4032c61cf881"}
tresses =  { url = 'https://github.com/wee-noise-makers/tresses', commit = "b067bc52c98b54d66999962619e04981d325c79f" }

[build-switches]
"*".ada_version = "ada2022"

[configuration.values]
noise_nugget_sdk.System_Clock = "SYS_133MHz"
littlefs.Assert = false
littlefs.Debug = false
littlefs.Warn = false
littlefs.Error = false
littlefs.Trace = false
littlefs.No_Malloc = true
tresses.Sample_Rate = "SR32000"
# tresses.Resources_Linker_Section = ".time_critical.tresses_resources"
# tresses.Code_Linker_Section = ".time_critical.tresses_code"
flux.Enable_File_IO = false

[build-profiles]
# noise_nugget_sdk = "development"
# rp2040_hal = "development"
# littlefs = "development"
