name = "wnm_pgb1_device"
description = "Firmware for the PGB-1 groovebox"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wnm_pgb1_device"]

[[depends-on]]
tresses = "^1.0.0"
littlefs = "~0.1.0"
flux = "~0.1.0-dev"
noise_nugget_sdk = "*"
midi = "^1.0.0"

[[pins]]
littlefs = { url = "https://github.com/Fabien-Chouteau/littlefs-ada", branch="release/0.3" }
tresses = { url = "git@github.com:wee-noise-makers/tresses.git", branch="release/1.0" }
flux = { url="https://github.com/Fabien-Chouteau/flux" }
# noise_nugget_sdk = { url = "git@github.com:wee-noise-maker/noise-nugget-ada-sdk.git" }
noise_nugget_sdk = { path = "../../noise-nugget-ada-sdk" }

[build-switches]
"*".ada_version = "ada2022"

[configuration.values]
noise_nugget_sdk.System_Clock = "SYS_133MHz"
littlefs.Assert = false
littlefs.Debug = false
littlefs.Warn = false
littlefs.Error = false
littlefs.Trace = false
littlefs.No_Malloc = true
tresses.Sample_Rate = "SR32000"
# tresses.Resources_Linker_Section = ".time_critical.tresses_resources"
# tresses.Code_Linker_Section = ".time_critical.tresses_code"
flux.Enable_File_IO = false

[build-profiles]
# noise_nugget_sdk = "development"
# rp2040_hal = "development"
# littlefs = "development"
