on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.

jobs:
  build_native:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: simulator
    steps:
    
      - uses: actions/checkout@v4

      - uses: alire-project/setup-alire@v4

      - run: alr build

      - name: Build ROM
        run: ./bin/wnm-pgb1-rom-tool build share/wnm_pgb1_simulator/rom_desc.toml WNM-PGB1-factory

      - name: Upload filesystem and samples UF2
        uses: actions/upload-artifact@v4
        with:
          name: Factory filesystem and samples
          path: |
            WNM-*.uf2
