name: Firmware Validation

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Alire
      uses: alire-project/setup-alire@v4
      
    - name: Alire Update
      working-directory: device/
      run: alr update

    - name: Alire Show
      working-directory: device/

    - name: Alire Build (validation)
      working-directory: device/
      run: alr build --validation
